### PR TITLE
Draft of interim governance doc

### PR DESCRIPTION
**Pull request by CoralineAda**
This document specifies the interim governance of our community, with the knowledge that in the future more comprehensive representation and leadership bylaws may be drafted.

### CODE REVIEW

**Comment by decentral1se** [comment]
Since I guess we're aware of the various downfalls and it is noted in the brief commentary that this is interim, I feel like there is space to play with here. 

Can't this just be straight shot "interim council" of the three members members mentioned in the Basics section assuming there is bandwidth from those mentioned? No bureaucracy needed just drop a few lines on it like you did for this model.

This could be interpreted as a knee-jerk reaction from my side but it ain't, proposal made it earnest and in the experience of being down and out finished with appealing to dictators in open source :no_entry_sign:

**Comment by IreneKnapp** [comment]
This is solid and I like it. That wording "in the spirit of collaboration rather than confrontation" is amazing and clearly drawn from experience. Thanks for taking the time to put this through peer review!

**Comment by decentral1se** [comment]
Just to link, was suggested via the chat

> "Temporary Benevolent Dictator (TBD)" 
> https://communityrule.info/create/?r=1589491067257

**Review by decentral1se — APPROVED** [review]

**Comment by juliana0101** [comment]
Quero colaborar e ajudar a resolver

**Comment by juliana0101** [comment]
Me ajuda que eu ajudo com o maior prazer

**Pull request merged**
