### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by gr2m**
Follow up for https://github.com/ContributorCovenant/ethicalsource/pull/3#issuecomment-538765931

Danke @thorva - these are great improvements, I learned a thing or two myself 😀

### CODE REVIEW

**Comment by CoralineAda** [comment]
🖤

**Comment by gr2m** [comment]
@thora The github.com website has all you need to suggest changes to text files, you don't need to understand git or install anything, your browser is enough :) 

When you open a file such as [content/definition/definition.de.md](https://github.com/ContributorCovenant/ethicalsource/blob/release/content/definition/definition.de.md), you will see a little pen icon on the top right

image

When you hit it, you can directly edit its content. But don't worry, you cannot break anything, you don't have write access to the original document. Instead, when you hit the <kbd>Propose File change</kbd>, a cope of the whole repository will be made to your account (a so called fork). 

image

The next screen will show you the differences you created and offer you to create a pull request

image

Just hit the big green button, edit the pull request title & body if you like, and you are all set. Feel free to ping me on https://twitter.com/gr2m or comment here if you have more questions. 

We certainly could use more contributors with your background right now, I'm happy to help you with the technicalities

**Comment by jdu9** [comment]
@thorva Why "Quellencode" and not "Quellcode"?

**Comment by gr2m** [comment]
Good question @thorva

**Comment by jdu9** [comment]
Apart from that, I'm a bit irritated about the translation of "freely" to "kostenlos". There's a duplicate "unserem", too.

**Comment by gr2m** [comment]
Valid points. It’s still an early draft, can you send a pull request and ping me? Happy to review the changes

**Comment by jdu9** [comment]
I'd prefer not to commit anything for a project promoting non-free software.

**Pull request merged**
