### PR TITLE
feat: first draft of Czech translation

### PR DESCRIPTION
**Pull request by hakamadare**

### CODE REVIEW

**Comment by JaroslavPolacek** [comment]
I'm sorry but this is unacceptable even as a first draft. The syntax and grammar are wrong and the word choices are questionable at best, such as using archaic mravouka instead of widely used etika for ethics, especially since this choice changes the connotation of the sentences making them sound somewhat condescending. 

Moreover some words such as "poskytová" or "považová" are not real words at all, they're obviously based on real verbs poskytovat and považovat, but they do not exist in the form that can be found in this draft. 

Interestingly enough, if we ignore the clumsiness of certain choices of words, a few phrases there almost seem like the typical Prague/Central Bohemian dialect ("mravoučnýho zdrojovýho kódu" instead of "mravoučného zdrojového kódu"), but even if that was indeed the case it still shouldn't be used in a document such as this one. 

Even just using Google Translate or any other similar online translator would yield a better result, albeit still far from perfect.

This seems to be done by someone who's currently going through the process of learning Czech, which would make this an admirable attempt, but incorrect nonetheless. In its current form it's very difficult to even figure out what is it supposed to say.

**Comment by hakamadare** [comment]
Ok!  Thank you for your review. I haven’t spoken or written Czech for several decades, so I am not surprised that I have made many errors. I would be happy to accept any edits you might make; it’s also fine if you would prefer that I simply close the PR.

**Comment by CoralineAda** [comment]
@JaroslavPolacek While I appreciate you reviewing the translation, your feedback wasn't particularly kind or constructive and is at odds with our code of conduct.

**Comment by hakamadare** [comment]
@JaroslavPolacek @CoralineAda I'd be very happy to accept edits :) I learned Czech from my mother rather than by formal instruction, and so I'm not surprised that I have Prague dialect features.

Let's iterate on this translation some more and see if we can get it into an acceptable state?

**Pull request closed without merging**
