### PR TITLE
Update Portuguese translation

### PR DESCRIPTION
**Pull request by ruan-brandao**
Update Portuguese translation to reflect changes on the revised
definition.

### CODE REVIEW

**Comment by CoralineAda** [comment]
Hi Ruan, we're iterating a bit more on the definition so if you don't mind holding off for another week to finalize the translation, that would be ideal.

**Comment by CoralineAda** [comment]
We merged the new copy last night, so go ahead and update! Thanks for waiting.

**Comment by ruan-brandao** [comment]
@CoralineAda I have updated the translation.

**Comment by CoralineAda** [comment]
Sorry @ruan-brandao , can you take one more pass?

**Comment by CoralineAda** [comment]
@ruan-brandao Any updates?

**Comment by ruan-brandao** [comment]
@CoralineAda I have pushed the translation of the revised definition.

**Comment by CoralineAda** [comment]
Great, thanks so much!

**Pull request merged**
