### PR TITLE
Translate code of conduct into French

### PR DESCRIPTION
**Pull request by tobie**

### CODE REVIEW

**Review by CoralineAda — APPROVED** [review]

**Review by CoralineAda — APPROVED** [review]
Preview: https://deploy-preview-71--ethicalsource.netlify.app/fr/community-code-of-conduct/

LGTM!

**Comment by tobie** [comment]
Should I rename the file to `code-de-conduite.fr.md` so it shows up as: `/fr/code-de-conduite/`?

**Comment by CoralineAda** [comment]
Yes, just try it in the deploy preview to make sure it works.

**Comment by tobie** [comment]
All set. Thanks.

**Pull request merged**
